@startuml "contract-negotiation-event-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractNegotiationEventMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dspace:ContractNegotiationEventMessage"
    dspace:processPid : String
    dspace:eventType : dspace:NegotiationEvent
}

enum dspace:NegotiationEvent {
    dspace:ACCEPTED
    dspace:FINALIZED
}

"dspace:ContractNegotiationEventMessage" "1" *-- "1" "dspace:NegotiationEvent" : "dspace:eventType"

@enduml