@startuml "contract-negotiation"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractNegotiation" {
    @context : "https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/main/common/schema/context.json"
    @type : "dspace:ContractNegotiation"
    dspace:processId : String
    dspace:state : dspace:ContractNegotiationState
}

enum dspace:ContractNegotiationState {
    "dspace:REQUESTED"
    "dspace:OFFERED"
    "dspace:ACCEPTED"
    "dspace:AGREED"
    "dspace:VERIFIED"
    "dspace:FINALIZED"
    "dspace:TERMINATED"
    "..."
}

"dspace:ContractNegotiation" "1" *-- "1" "dspace:ContractNegotiationState" : "dspace:contractNegotiationState"

@enduml
