@startuml "contract-negotiation"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractNegotiation" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dspace:ContractNegotiation"
    dspace:processPid : String
    dspace:state : dspace:ContractNegotiationState
}

enum dspace:ContractNegotiationState {
    "dspace:REQUESTED"
    "dspace:OFFERED"
    "dspace:ACCEPTED"
    "dspace:AGREED"
    "dspace:VERIFIED"
    "dspace:FINALIZED"
    "dspace:TERMINATED"
    "..."
}

"dspace:ContractNegotiation" "1" *-- "1" "dspace:ContractNegotiationState" : "dspace:contractNegotiationState"

@enduml
