@startuml "contract-request-message_initial"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractRequestMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : dspace:ContractRequestMessage
    dspace:dataset : String
    dspace:consumerPid : String
    dspace:callbackAddress : String
}

class odrl:Offer {
    @type : odrl:Offer,
    @id: String
    odrl:target : xsd:anyURI
    ...
}

"dspace:ContractRequestMessage" "1" *-- "*" "odrl:Offer" : "dspace:offer"

@enduml