@startuml "contract-agreement-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractAgreementMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dspace:ContractAgreementMessage"
    dspace:processPid : String
    dspace:agreement : odrl:Agreement
    dspace:callbackAddress : xsd:anyURI
}

class odrl:Agreement {
    @type : "odrl:Agreement"
    @id: String
    odrl:target : xsd:anyURI
    dspace:timestamp : xsd:dateTime
    dspace:consumerId : String
    dspace:providerId : String
}

"dspace:ContractAgreementMessage" "1" *-- "1" "odrl:Agreement" : "odrl:agreement"

@enduml
