@startuml "contract-request-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractRequestMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : dspace:ContractRequestMessage
    dspace:dataSet : String
    dspace:processPid : String
    dspace:offer : odrl:Offer
    dspace:callbackAddress : String
}

class odrl:Offer {
    @type : odrl:Offer,
    @id: String
    odrl:target : xsd:anyURI
}

"dspace:ContractRequestMessage" "1" *-- "1" "odrl:Offer" : "dspace:offer"

@enduml