@startuml "contract-agreement-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractAgreementMessage" {
    @context : "https://w3id.org/dspace/2024/1/context.json"
    @type : "dspace:ContractAgreementMessage"
    dspace:providerPid : String
    dspace:consumerPid : String
    dspace:callbackAddress : xsd:anyURI
}

class odrl:Agreement {
    @type : "odrl:Agreement"
    @id: String
    odrl:target : xsd:anyURI
    dspace:timestamp : xsd:dateTime
    odrl:assignee : String
    odrl:assigner : String
}

"dspace:ContractAgreementMessage" "1" *-- "1" "odrl:Agreement" : "dspace:agreement"

@enduml
