@startuml "contract-negotiation-termination-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:ContractNegotiationTerminationMessage" {
    @context : "https://raw.githubusercontent.com/simantvermasap/ids-specification/main/common/schema/context.json"
    @type : "dspace:ContractNegotiationTerminationMessage"
    dspace:providerPid : String
    dspace:consumerPid : String
    dspace:code : String
    dspace:reason : Array
}

@enduml