@startuml "catalog-error-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:CatalogErrorMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dspace:CatalogErrorMessage"
    dspace:code : String
    dspace:reason : Array
}

@enduml