@startuml "catalog-request-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:CatalogRequestMessage" {
    @context : "https://raw.githubusercontent.com/simantvermasap/ids-specification/main/common/schema/context.json"
    @type : dspace:CatalogRequestMessage
    dspace:filter : Object
}

@enduml