@startuml "catalog"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class dcat:Catalog {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dcat:Catalog"
    foaf:homepage : String
    dcat:theme : Array<String>
    dcat:keyword : Array<String>
    dct:conformsTo : String
    dct:creator : String
    dct:identifier : String
    dct:issued : String
    dct:modified : String
    dct:title : String
    dspace:participantId : String
    dct:description : Array<MultilanguageText>
    ...
}

"dcat:Catalog" "0" *-- "*" "dcat:Dataset" : "dcat:dataset"

"dcat:Catalog" "0" *-- "*" "dcat:DataService" : "dcat:service"

"dcat:Catalog" "0" --> "*" "odrl:Offer" : "odrl:hasPolicy"


class dcat:Dataset {
    @type : "dcat:Dataset",
    dcat:theme : Array<String>
    dcat:keyword : Array<String>
    dct:conformsTo : String
    dct:creator : String
    dct:identifier : String
    dct:issued : String
    dct:modified : String
    dct:title : String
    dct:description : Array<MultilanguageText>
    ...
}

"dcat:Dataset" "1" --> "*" "odrl:Offer" : "odrl:hasPolicy"

"dcat:Dataset" "0" --> "*" "dcat:Distribution" : "dcat:distribution"

class dcat:DataService {
    dcat:endpointDescription : String
    dcat:endpointURL : String
    dcat:theme : Array<String>
    dcat:keyword : Array<String>
    dct:conformsTo : String
    dct:creator : String
    dct:identifier : String
    dct:issued : String
    dct:modified : String
    dct:title : String
    dct:description : Array<MultilanguageText>
    ...
}

"dcat:DataService" "0" --> "*" "dcat:Dataset" : "dcat:servesDataset"

"dcat:DataService" "0" --> "*" "odrl:Offer" : "odrl:hasPolicy"


class dcat:Distribution {
    @type : "dcat:Distribution",
    dct:title : String
    dct:description : Array<MultilanguageText>
    dct:issued : String
    dct:modified : String
    ...
}

"dcat:Distribution" "0" --> "*" "odrl:Offer" : "odrl:hasPolicy" 

"dcat:Distribution" "1" --> "*" "dcat:DataService" : "dcat:accessService"


@enduml