@startuml "catalog-request-message"
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml

hide empty description


class "ids:CatalogRequestMessage" {
    @context : "https://w3id.org/idsa/v5/context.json"
    @type : ids:CatalogRequestMessage
    ids:filter : ids:Filter
}

class ids:Filter {
    @type : "ids:Filter",
    @id: String
    ...
}

"ids:CatalogRequestMessage" "1" *-- "0..n" "ids:Filter" : "ids:filter"

@enduml