@startuml "transfer-termination-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferTerminationMessage" {
    @context : "https://w3id.org/dspace/2024/1/context.json"
    @type : "dspace:TransferTerminationMessage"
    dspace:providerPid : String
    dspace:consumerPid : String
    dspace:code : String
    dspace:reason : Array
}

@enduml