@startuml "transfer-error"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferError" {
    @context : "https://w3id.org/dspace/2024/1/context.json"
    @type : "dspace:TransferError"
    dspace:providerPid : String
    dspace:consumerPid : String
    dspace:code : String
    dspace:reason : Array
}

@enduml