@startuml "transfer-termination-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferTerminationMessage" {
    @context : "https://raw.githubusercontent.com/International-Data-Spaces-Association/ids-specification/main/common/schema/context.json"
    @type : "dspace:TransferTerminationMessage"
    dspace:processId : String
    dspace:code : String
    dspace:reason : Array
}

@enduml