@startuml "transfer-start-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferStartMessage" {
    @context : "https://w3id.org/dspace/1/0/context.json"
    @type : "dspace:TransferStartMessage"
    dspace:processId : String
    dspace:correlationId : String
    dspace:dataAddress : String
}

@enduml