@startuml "transfer-start-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferStartMessage" {
    @context : "https://w3id.org/dspace/v0.8/context.json"
    @type : "dspace:TransferStartMessage"
    dspace:providerPid : String
    dspace:consumerPid : String
    dspace:dataAddress : String
}

@enduml