@startuml "transfer-process"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "ids:TransferProcess" {
    @context : "https://w3id.org/idsa/v5/context.json"
    @type : "ids:TransferProcess"
    ids:correlationId : String
    ids:state : ids:TransferState
}


enum ids:TransferState {
    "ids:REQUESTED"
    "ids:STARTED"
    "ids:TERMINATED"
    "ids:COMPLETED"
    "ids:SUSPENDED"
}

"ids:TransferProcess" "1" *-- "1" "ids:TransferState" : "ids:transferState"

@enduml