@startuml "transfer-request-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferRequestMessage" {
    @context : "https://w3id.org/dspace/1/0/context.json"
    @type : "dspace:TransferRequestMessage"
    dspace:agreementId : String
    dct:format : String
    dspace:dataAddress : String
    dspace:callbackAddress : String
}

@enduml