@startuml "transfer-error"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferError" {
    @context : "https://w3id.org/dspace/1/0/context.json"
    @type : "dspace:TransferError"
    dspace:processId : String
    dspace:correlationId : String
    dspace:code : String
    dspace:reason : Array
}

@enduml