@startuml "transfer-completion-message"
!pragma layout smetana

!include ../../../common/style/diagram.styles.puml

hide empty description


class "dspace:TransferCompletionMessage" {
    @context : "https://raw.githubusercontent.com/simantvermasap/ids-specification/main/common/schema/context.json"
    @type : "dspace:TransferCompletionMessage"
    dspace:providerPid : String
    dspace:consumerPid : String
}

@enduml