@startuml "contract-negotiation-termination-message"
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml

hide empty description


class "ids:ContractNegotiationTerminationMessage" {
    @context : "https://w3id.org/idsa/v5/context.json"
    @type : "ids:ContractNegotiationTerminationMessage"
    ids:processId : String
    ids:code : Object
    ids:reason : Array
}

@enduml