@startuml "contract-negotiation-state-machine"
!pragma layout smetana

!include ../common/style/diagram.styles.puml

hide empty description

state REQUESTED
state OFFERED
state ACCEPTED
state AGREED
state VERIFIED
state FINALIZED
state TERMINATED $lightRed #$borderRed: <color:$darkGray>ContractNegotiationTerminationMessage

[*] --> REQUESTED: C:ContractRequestMessage
[*] --> OFFERED: P:ContractOfferMessage

REQUESTED -->  OFFERED: P:ContractOfferMessage
REQUESTED -->  AGREED: P:ContractAgreementMessage

OFFERED -->  REQUESTED: C:ContractRequestMessage
OFFERED -->  ACCEPTED: C:ContractNegotiationEventMessage.accepted

ACCEPTED --> AGREED: P:ContractAgreementMessage

AGREED --> VERIFIED: C:ContractAgreementVerificationMessage

VERIFIED --> FINALIZED: P:ContractNegotiationEventMessage.finalized

FINALIZED --> [*]

TERMINATED --> [*]

@enduml
