@startuml "contract-negotiation-state-machine"
!pragma layout smetana

!include ../common/style/diagram.styles.puml

hide empty description

state REQUESTED
state OFFERED
state ACCEPTED
state AGREED
state VERIFIED
state FINALIZED
state TERMINATED $lightRed #$borderRed

[*] --> REQUESTED: C:ContractRequestMessage
[*] --> OFFERED: P:ContractOfferMessage

REQUESTED -->  OFFERED: P:ContractOfferMessage
REQUESTED -->  AGREED: P:ContractAgreementMessage
REQUESTED --> TERMINATED: C/P:ContractNegotiationTerminationMessage

OFFERED -->  REQUESTED: C:ContractRequestMessage
OFFERED -->  ACCEPTED: C:ContractNegotiationEventMessage.accepted
OFFERED -->  TERMINATED: C/P:ContractNegotiationTerminationMessage

ACCEPTED --> AGREED: P:ContractAgreementMessage
ACCEPTED -> TERMINATED: P:ContractNegotiationTerminationMessage

AGREED --> VERIFIED: C:ContractAgreementVerificationMessage
AGREED --> TERMINATED: C:ContractNegotiationTerminationMessage

VERIFIED --> FINALIZED: P:ContractNegotiationEventMessage.finalized
VERIFIED -> TERMINATED: P:ContractNegotiationTerminationMessage

FINALIZED -->[*]

TERMINATED --> [*]

@enduml
