@startuml "transfer-start-message"
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml

hide empty description


class "ids:TransferStartMessage" {
    @context : "https://w3id.org/idsa/v5/context.json"
    @type : "ids:TransferStartMessage"
    ids:processId : String
    ids:correlationId : String
    ids:dataAddress : String
}

@enduml