@startuml "transfer-completion-message"
!pragma layout smetana

!include ../../diagrams/diagram.styles.puml

hide empty description


class "ids:TransferCompletionMessage" {
    @context : "https://w3id.org/idsa/v5/context.json"
    @type : "ids:TransferCompletionMessage"
    ids:processId : String
    ids:correlationId : String
}

@enduml