@startuml "pull-transfer-process"
!pragma layout smetana

!include ../common/style/diagram.styles.puml

hide empty description

skinparam defaultTextAlignment center

box Consumer
participant Connector1
end box

box Provider
participant Connector2
end box

activate Connector1
activate Connector2

Connector1 -> Connector2 : TransferRequestMessage
Connector2 --> Connector1 : ACK

Connector2 -> Connector1 : TransferStartMessage(dataAddress)
Connector1 --> Connector2 : ACK

Connector1 -> Connector2 : pullData
Connector2 --> Connector1 : data

Connector1 -> Connector2 : TransferCompletionMessage
Connector2 --> Connector1 : ACK

deactivate Connector1
deactivate Connector2

@enduml
