@startuml "pull-transfer-process"
!pragma layout smetana

!include ../common/style/diagram.styles.puml

hide empty description

skinparam defaultTextAlignment center

box Consumer
participant DataPlane1
participant ControlPlane1
end box

box Provider
participant ControlPlane2
participant DataPlane2
end box

activate ControlPlane1
activate ControlPlane2

ControlPlane1 -> ControlPlane2 : TransferRequestMessage
ControlPlane2 --> ControlPlane1 : ACK

ControlPlane2 -> ControlPlane1 : TransferStartMessage(dataAddress)
ControlPlane1 --> ControlPlane2 : ACK

activate DataPlane1
DataPlane1 -> DataPlane2 : pullData
activate DataPlane2
DataPlane2 --> DataPlane1 : data
deactivate DataPlane2
deactivate DataPlane1

ControlPlane1 -> ControlPlane2 : TransferCompletionMessage
ControlPlane2 --> ControlPlane1 : ACK

deactivate ControlPlane1
deactivate ControlPlane2

@enduml
