@startuml "push-transfer-process"
!pragma layout smetana

!include ../common/style/diagram.styles.puml

hide empty description

skinparam defaultTextAlignment center

box Consumer
participant Connector1
end box

box Provider
participant Connector2
end box

activate Connector2

Connector1 -> Connector2 : TransferRequestMessage(dataAddress)
Connector2 --> Connector1 : ACK

Connector2 -> Connector1 : TransferStartMessage
Connector1 --> Connector2 : ACK

Connector2 -> Connector1 : pushData(data)

Connector1 --> Connector2 : ACK

Connector2 -> Connector1 : TransferCompletionMessage
Connector1 --> Connector2 : ACK

deactivate Connector1
deactivate Connector2

@enduml
