@startuml "hub-request-processing"
!pragma layout smetana

!include ../diagrams/diagram.styles.puml

hide empty description

state REQUESTED: <color:$darkGray>TransferRequestMessage
state STARTED: <color:$darkGray>TransferStartMessage
state COMPLETED: <color:$darkGray>TransferCompletionMessage
state SUSPENDED: <color:$darkGray>TransferSuspensionMessage

state TERMINATED $lightRed #$borderRed : <color:$darkGray>TransferTerminationMessage

[*] --> REQUESTED: C
REQUESTED -->  STARTED: P
STARTED -->  COMPLETED: P/C
STARTED -->  SUSPENDED: P/C
SUSPENDED --> STARTED: P/C
COMPLETED -->[*]

TERMINATED --> [*]

@enduml
