name: Validate JSON Schemas
on: 
  push:
    branches:
      - main
      - shapes-and-schemas-subtask
  pull_request:
    branches:
      - main
      - shapes-and-schemas-subtask   
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON Schema
        run: |
          top_level_folders=(catalog negotiation transfer)
          for folder in "${top_level_folders[@]}"; do
            echo "Validating schemas in folder: $folder"
            schemas=$(find "$folder/message/schema" -name "*-schema.json")
            for schema in $schemas; do
              json_file=${schema#"$folder/message/schema/"}
              json_file=${json_file%-schema.json}            # Remove ".schema.json"
              json_file_path="$folder/message/$json_file.json"  # Construct correct path
              
              echo "Validating $json_file_path with $schema"
              uses: walbo/validate-json@v1.1.0
                with:
                  files: $json_file_path
                  schema: $schema
                  schema-version: draft-04
                  print-valid-files: false
                  fail-on-missing-schema: false
                  strict: true
                  allow-matching-properties: false
                  allow-union-types: true
            done
          done
