name: Validate JSON Schemas
on: 
  push:
    branches:
      - main
      - shapes-and-schemas-subtask
  pull_request:
    branches:
      - main
      - shapes-and-schemas-subtask   
jobs:
  validate-json:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        folders:
          - catalog/message
          - negotiation/message
          - transfer/message
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      #- name: Validate JSON Schema
      #  uses: dsanders11/json-schema-validate-action@v1.1.2
      #  with:
      #    schema: ${{ matrix.schema }}
      #    files: ${{ matrix.example }}
      #    fail-on-invalid: true
      - name: Bash to execute the JSON Schema Checks
        run: |
          sudo pipx install check-jsonschema

          for folder in ${{ matrix.folders }}
          do
            echo $folder
            for json_file in $folder/*.json
            do
              echo $json_file
              _base_filename=$(basename "$json_file" .json)  # Remove .json extension
              schema_file="$folder/schema/${_base_filename}-schema.json"
              echo $schema_file
              if [[ -f "$schema_file" ]]; then
                echo "Validating $json_file against $schema_file"
                check-jsonschema --schemafile "$schema_file" "$json_file"
              else
                echo "WARNING: Schema file not found for $json_file"
              fi
            done
          done
