name: Validate JSON Schemas
on: 
  push:
    branches:
      - main
      - shapes-and-schemas-subtask
  pull_request:
    branches:
      - main
      - shapes-and-schemas-subtask   
jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON Schema
        run: |
          top_level_folders=(catalog negotiation transfer)
          for folder in "${top_level_folders[@]}"; do
            echo "Validating schemas in folder: $folder"
            schemas=$(find "$folder/message/schema" -name "*-schema.json")
            for schema in $schemas; do
              echo "$schema test"
              
              json_file=${schema%*-schema.json}  # Remove "-schema.json"
              json_file_path="$folder/message/$json_file.json"  # Construct path to JSON file
              echo "$json_file_path test"
              
              echo "Validating $json_file with $schema"
              uses: jakejarvis/json-schema-validate@v4
                with:
                  schema: $schema
                  files: $json_file_path
                  fail-on-invalid: true
            done
          done
